[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/15WhpXDecY5QJQDFEu_Uh4fsSLDr3fA7cinSTlLAu8f8/edit?usp=sharing"
type = "service_account"
project_id = "jateng-harvest-monitoring"
private_key_id = "4514d360f31e314abea27205d0786068735a02a2"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDsHRBJlmJ5fRiC
8r0Pd8tEgvR1e3gstQEwGKrYJc9Hzqdm5uRtZIICABTIiS8kI6YYyivIRzZxsSKv
XLpYC9xnXFQw+O3YJPwFBpR+2a1L/cynXV+b4S/3o0JNmo9opqqtJ8esvTacdkuS
lSFYiW9b6gYN0r/sUHdum8h26hKjUR7N9xkYWF3qg1cMZ+s7g1bw7W6z9dIx2SA0
tXPjnIZ4QboCMirgS2mr8CwUHQEvHlaNEWQlhjVd8zBImxtMVAdb7CWvNOuCTGXY
8Cxb3HDAYwJNLVCaYBe8X4OM2Hy86Eb59/bbSXIXIxcEQR3B777ygQNo4szezvg8
fjpaJgMpAgMBAAECggEAKtW8+jSrqdGtjDggX3mCqWu+kL+1FhtCW2jmOa9mUucl
TJBP2Z61zUoZeyYUJNDI1c97sOpmcKrLmZfPgKCqPCAub/IBKEjRZdIDR54TB+nD
4osYiM2KJ7l5El4bbUdrSF2ipm5vRWRaon2mnorUZo7myUQ2KFeSy0C81gHyHqmE
FDZzzWYnV96txAGVVHT6Dw1/CVEZt+Zy0bovCy7wA9QzvjmmY81OrG2WpU+9wgbc
wKAp786FAfxGhW1iTYAMdnAJgexcnx/wRl87Hk4S92UD1cTAZ4ruvW2YpKnkfqhf
Bs8iOOc+tXV4Tj7RqA2AQxSLB3H1gR2XLjECp3TyvwKBgQD+hWqLW1rwnlqMGEbX
vcMZbZLaY8W1MjKzm5jmuaA3/SsPnfJi+UG8zsTRSBnDMRMWoatZpgQ/2i7NsU5p
ojCtiN+0PXnVDLcABT7r4NQRhJ8qgdgHJwDZ9mkzGE3DXf5s2HKcFcthWu9fy+4+
/+FoSoEGRvLFU78JHqvCu5DNdwKBgQDtfERsJvKqrD5gE9k3yunhzzKdYc8BRtR5
wAejbjg5iRyYk2UXuJ9HAO1+J2qwctbsABefHt/wDmyvz0tobWaQBQ5GRjUd/CIe
pcPuRaxZ0aWbjbJzUAKH6NuPSiU4gMZabxMFZdmKO84ieZ2ZAliSm/fN74AF7T6L
KSTGb8VcXwKBgQDgmgl4aqiol4UeBbpWXc3SHaCu+caZbG/TkWZvjLU3U0Dxqhcg
ggchv3FtoWuilSbcHNSh6t/rHPWabHHew9KjAJswaeOeP3cqHHb3HlLmFpuCnkxt
m1yj+0/AWB0fX03K7YLN/GmaQu3kIojerV1TdBPB31ATFCELwjYeRPi2ZwKBgFGW
Vp9dRhMSd59kUkTTpkQYfcgJ2ScUIVzudvFTpWdGzpcwVBOxLq8jB3RGsGWMHoAX
jAXzgnWjTv2bVsm6g/jIc936srbpbwNeaZCLSSnWV3G4XW02OJhejEeO7niZ7QsW
i89X7UOLRkcbxuPRJYLAqIKMXEws9Ea0zNiLf587AoGBALaARYBRqbR3GepBQAq2
7HUZI6eP5GOuibpFb+UucpRXU4qjS3p+ohV86Vn4xX2KpFL713JQCqIA2WdPY/qo
/vPm19awmIIRZlP07dZKd9tbKmMJFrBUO1qyDBOKtsE9xto+ei4whEUP73aUJ0Fi
YwHaXzLM18d2Nq6p3KXlST8K
-----END PRIVATE KEY-----"""
client_email = "jateng-harvest-bot@jateng-harvest-monitoring.iam.gserviceaccount.com"
client_id = "113931998841937767776"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/jateng-harvest-bot%40jateng-harvest-monitoring.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
